### ISSUE TITLE
Mirror `linux-mirrors.fnal.gov` is not available through IPv6

### ISSUE THREAD

**Issue by soksanichenko** [AlmaLinux/mirrors#688]
The service uses `aiohttp` for checking availability a mirror and `linux-mirrors.fnal.gov` is not available through async client. We get timeout exception.

**Comment by jcpunk** [comment]
Are there server settings I should tweak?  There is an F5 between the world and the servers (so I scale hosts as needed).  I don't manage that box, however.

**Comment by soksanichenko** [comment]
Hi.
Looks like your mirror banned our service, because it did many requests. The service did it because it checks every hour availability of a mirror. It checks that repomd.xml and ISO's artifacts are available per each version, arch and repository.

**Comment by jcpunk** [comment]
That should be well within our site limits... I'm serving all of EPEL off the same hosts...

**Comment by soksanichenko** [comment]
I just checked a few VMs and issue with access exists only on VM there is the service is deployed 🤔

**Comment by jcpunk** [comment]
It looks like you're running an 'OPTIONS' query:
`
 [08/Dec/2022:06:15:38 -0600] "OPTIONS /linux/almalinux/ HTTP/1.1" 403 218 "-" "python-requests/2.26.0"
`

Which I'd turned off.  I'll see about getting that turned back on.

**Comment by soksanichenko** [comment]
It was test manual request.
I ran next update manually.

**Comment by soksanichenko** [comment]
And again
`Mirror "linux-mirrors.fnal.gov" is not available by url "http://linux-mirrors.fnal.gov/linux/almalinux/" because "Connection timeout to host http://linux-mirrors.fnal.gov/linux/almalinux/"`
Does exist something interesting in logs of your mirror?

**Comment by jcpunk** [comment]
I've just kicked the servers to permit the OPTIONS request, can you try again?

**Comment by ZelGray** [comment]
Yes. Let me try.

**Comment by soksanichenko** [comment]
The same error. Any errors/warnings/etc in logs?

**Comment by jcpunk** [comment]
hmmmm, nothing new:
```
grep '34.207.21.30' *_log
access_log:34.207.21.30 - - [08/Dec/2022:05:10:56 -0600] "GET /linux/almalinux/ HTTP/1.1" 200 6676 "-" "curl/7.61.1"
access_log:34.207.21.30 - - [08/Dec/2022:05:11:16 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "curl/7.61.1"
access_log:34.207.21.30 - - [08/Dec/2022:05:54:31 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "python-requests/2.26.0"
access_log:34.207.21.30 - - [08/Dec/2022:06:00:06 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "curl/7.61.1"
access_log:34.207.21.30 - - [08/Dec/2022:06:08:18 -0600] "GET /linux/almalinux/ HTTP/1.1" 200 6676 "-" "curl/7.61.1"
access_log:34.207.21.30 - - [08/Dec/2022:06:15:38 -0600] "OPTIONS /linux/almalinux/ HTTP/1.1" 403 218 "-" "python-requests/2.26.0"
```

and:
```
Dec  8 05:54:31 linux-mirror01.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:05:54:31 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "python-requests/2.26.0"
Dec  8 05:54:31 linux-mirror01.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:05:54:31 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "python-requests/2.26.0"
Dec  8 06:08:18 linux-mirror01.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:06:08:18 -0600] "GET /linux/almalinux/ HTTP/1.1" 200 6676 "-" "curl/7.61.1"
Dec  8 06:15:38 linux-mirror01.fnal.gov httpd[1442]: [access_compat:error] [pid 1442] [client 34.207.21.30:59898] AH01797: client denied by server configuration: /srv/linux/almalinux/
Dec  8 06:15:38 linux-mirror01.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:06:15:38 -0600] "OPTIONS /linux/almalinux/ HTTP/1.1" 403 218 "-" "python-requests/2.26.0"
Dec  8 06:15:38 linux-mirror01.fnal.gov httpd[1442]: [access_compat:error] [pid 1442] [client 34.207.21.30:59898] AH01797: client denied by server configuration: /srv/linux/almalinux/
Dec  8 06:15:38 linux-mirror01.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:06:15:38 -0600] "OPTIONS /linux/almalinux/ HTTP/1.1" 403 218 "-" "python-requests/2.26.0"
Dec  8 05:10:57 linux-mirror02.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:05:10:56 -0600] "GET /linux/almalinux/ HTTP/1.1" 200 6676 "-" "curl/7.61.1"
Dec  8 05:10:57 linux-mirror02.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:05:10:56 -0600] "GET /linux/almalinux/ HTTP/1.1" 200 6676 "-" "curl/7.61.1"
Dec  8 05:11:16 linux-mirror02.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:05:11:16 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "curl/7.61.1"
Dec  8 05:11:16 linux-mirror02.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:05:11:16 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "curl/7.61.1"
Dec  8 06:00:06 linux-mirror02.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:06:00:06 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "curl/7.61.1"
Dec  8 06:00:06 linux-mirror02.fnal.gov httpd: 34.207.21.30 - - [08/Dec/2022:06:00:06 -0600] "HEAD /linux/almalinux/ HTTP/1.1" 200 - "-" "curl/7.61.1"

```

**Comment by soksanichenko** [comment]
Thank you!
Looks like the issue on our side. I will continue investigation tomorrow.

**Comment by soksanichenko** [comment]
@jcpunk 
Hello.
I found the root of issue.
Your mirror is available by IPv6. And the python network library tries to use IPv6 as main protocol if it's available for a site. 
But the mirror doesn't work by IPv6 although it has IPv6 record for the domain name

```
[ec2-user@ip-172-30-17-126 ~]$  curl --ipv6 -v linux-mirrors.fnal.gov
* Rebuilt URL to: linux-mirrors.fnal.gov/
*   Trying 2620:6a:0:105::105:75...
* TCP_NODELAY set
* connect to 2620:6a:0:105::105:75 port 80 failed: Connection timed out
* Failed to connect to linux-mirrors.fnal.gov port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to linux-mirrors.fnal.gov port 80: Connection timed out
[ec2-user@ip-172-30-17-126 ~]$  curl --ipv4 -v linux-mirrors.fnal.gov
* Rebuilt URL to: linux-mirrors.fnal.gov/
*   Trying 131.225.105.75...
* TCP_NODELAY set
* Connected to linux-mirrors.fnal.gov (131.225.105.75) port 80 (#0)
> GET / HTTP/1.1
> Host: linux-mirrors.fnal.gov
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 09 Dec 2022 12:43:20 GMT
< Server: Apache
< Last-Modified: Thu, 01 Sep 2022 19:52:10 GMT
< ETag: "800-5e7a2f2f88e7d"
< Vary: Accept-Encoding,User-Agent
< Content-Security-Policy: default-src 'self'; frame-ancestors 'none';
< Content-Length: 990
< Content-Type: text/html;charset=UTF-8
<
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>Index of /</title>
<link rel="stylesheet" href="/icons/index-hover-grey.css" type="text/css" /> </head>
 <body>
<h1>Index of /</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.png" alt="[ICO]" /></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th></tr>
   <tr><th colspan="4"><hr /></th></tr>
<tr><td valign="top"><img src="/icons/folder.png" alt="[DIR]" /></td><td><a href="linux/">linux/</a></td><td align="right">2022-11-29 10:26  </td><td align="right">  - </td></tr>
<tr><td valign="top"><img src="/icons/image.png" alt="[IMG]" /></td><td><a href="favicon.ico">favicon.ico</a></td><td align="right">2007-09-28 07:56  </td><td align="right">1.1K</td></tr>
   <tr><th colspan="4"><hr /></th></tr>
</table>
</body></html>
* Connection #0 to host linux-mirrors.fnal.gov left intact
[ec2-user@ip-172-30-17-126 ~]$
```

**Comment by soksanichenko** [comment]
I will force using IPv4 during checks of mirrors availability (it doesn't matter which protocol we use for the checks).

**Comment by jonathanspw** [comment]
> I will force using IPv4 during checks of mirrors availability (it doesn't matter which protocol we use for the checks).

I don't think that's the best approach.  Since most systems will default to IPv6 if there's a record, we should check that it properly works as not doing so will result in errors for users.

**Comment by jcpunk** [comment]
The mirror should be working over IPv6, I'll check with our network
folks....

**Comment by soksanichenko** [comment]
@jcpunk hi.
No, it's still not available from AWS (us-east-1). I used curl for checking (as above).

**Comment by soksanichenko** [comment]
https://ready.chair6.net/?url=linux-mirrors.fnal.gov

**Comment by jcpunk** [comment]
I think our firewall/routing is sorted for IPv6.  That site seems to show connectivity now.

**Comment by soksanichenko** [comment]
The mirror is in the list and available. Thank you.
